name: First Flow 
on: workflow_dispatch #--> Event
jobs:
  first-job: 
    runs-on: ubuntu-latest #-->  define OS
    steps:
      - name: print A7A
        run: echo "A7A" # --> shell command
      - name: printing toz feek
        run: echo "toz feek"

  second-job:
    needs: first-job
    runs-on: ubuntu-latest #-->  define OS
    steps: 
      - name: pending step 1
        run: echo "2nd job is done"
